### ISSUE TITLE
Is this still being worked on?

### ISSUE THREAD

**Issue by surfjedi** [ay13/webpack-angular-oclazyload#3]
Hi,

I am doing some work and have started with your project and added some features for a demo. 

Are you interested in PR's and updates ?

**Comment by ay13** [comment]
Thanks for the PR. 

I have not worked on this for a long time. I put it up as a demo of everything working together and haven't touched it since. I am glad it has helped someone.

**Comment by surfjedi** [comment]
Of course - I have gone a bit further with adding bigger libraries like material design, etc.  

Have a look: 
https://github.com/berzerk-interactive/webpack-angular-oclazyload/tree/feature/material-design

Have you been making bigger apps with this?

**Comment by ay13** [comment]
No, I haven't. I use webpack for almost everything I make but I have been slowly moving away from Angular so haven't used it in any big projects recently.
